version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - airflow-network

  airflow-init:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
    networks:
      - airflow-network

  airflow-webserver:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    command: webserver
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    networks:
      - airflow-network

  airflow-scheduler:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    command: scheduler
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    networks:
      - airflow-network

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - airflow-webserver
    networks:
      - airflow-network

networks:
  airflow-network:
    driver: bridge